### PR TITLE
centos: remove python-redis

### PR DESCRIPTION
**Pull request by manics**
This is a python 2 package

### CODE REVIEW

**Comment by joshmoore** [comment]
Hmmm.... looking at travis, why are those labeled Py36 if using Py35? Re: the dropping of python3.5 itself, we likely should split https://docs.openmicroscopy.org/omero/5.6.2/sysadmins/version-requirements.html?highlight=requirements#python for web versus server. (Obviously, it would have been nice to _warn_ that it was going to be dropped...)

Finally to this PR: is the installation of python-redis python3+ a no-op or a failure? If a failure, why didn't we notice this sooner?

**Comment by manics** [comment]
Looks like it's set in `.travis.yml` even though it's not (AFAIK) necessary.

`python-redis` is an unnecessary dependency, it's for Python 2 only. The Python 3 module is automatically pulled in as a dependency in the virtualenv if you install django-redis.

**Comment by manics** [comment]
Also the Python versions for server and web are the same, in this case it's the latest release of OMERO.py that broken Pytohn 3.5

**Comment by manics** [comment]
Actually I was wrong, Python is required to _build_ the docs but not to run the tests since they're in Docker:
https://github.com/ome/omeroweb-install/blob/47840fa8b7eba2ece1ddc32d72a462174400320f/.travis/before_install.sh#L66-L70

**Comment by jburel** [comment]
Travis is back to green after releasing omero-py and omero-web.
Merging this PR so it can be included in the doc

**Pull request merged**
