### PR TITLE
install jinja2

### PR DESCRIPTION
**Pull request by jburel**
install jinja2 using the package manager
The changes match what is currently installed using https://github.com/ome/omero-install
see https://trello.com/c/QaxIg0AH/156-jinja-warning

cc @joshmoore @mtbc

### CODE REVIEW

**Comment by mtbc** [comment]
Diff looks good.

**Comment by joshmoore** [comment]
Will someone who's only installing the server still see the errors?

(In the future, I'd say, that my question would be covered by `pip install omero-web` installing jinja, but in the interim, ...)

**Comment by jburel** [comment]
@joshmoore it depends which instructions the person is following. If he/she follows https://docs.openmicroscopy.org/omero/5.5.0-rc1/sysadmins/unix/server-installation.html
then the person won't see the error since ``python-jinja2`` is installed.

**Comment by rgozim** [comment]
Looks good 👍

`jinja2` is also pip installable, do we need to make this a part of the [requirements.txt](https://github.com/openmicroscopy/openmicroscopy/blob/develop/components/tools/OmeroWeb/requirements-py27-all.txt) for OmeroWeb, as that will be what OSX users will be using?

**Comment by jburel** [comment]
I had an initial PR for that. OS X installation is not solely for development (not recommended for production)
So I opted to only synch omero-install and omero-web i.e. not using pip

**Comment by joshmoore** [comment]
> If web installed separately from the server, this is possible that the error will be thrown without this PR

This might be something for https://github.com/openmicroscopy/openmicroscopy/pull/5994, but I'm strongly of the opinion that **either**:
 - no route to installation should allow jinja to **not** be installed (including upgrade)
 - **or** we hide that message

**Comment by mtbc** [comment]
jinja2 should be among https://docs.openmicroscopy.org/omero/5.4.10/sysadmins/unix/install-web/web-deployment.html#prerequisites ?

**Comment by jburel** [comment]
is jinja2 installed when using ansible?

**Comment by jburel** [comment]
ansible web role requires a change in the requirements file see https://github.com/openmicroscopy/openmicroscopy/pull/6034

**Comment by jburel** [comment]
web-docker uses ansible python deps role. The role installs jinja2

**Comment by jburel** [comment]
the only place not installing jinja2 is this repository, That point is missing from our doc

**Comment by jburel** [comment]
Discussed this am, ``ansible-role-omero-server`` and ``ansible-role-omero-web`` use omero-python-deps which will install ``python-jinja2``
see 
* https://github.com/openmicroscopy/ansible-role-omero-web/blob/master/meta/main.yml#L23
* https://github.com/openmicroscopy/ansible-role-omero-server/blob/master/meta/main.yml#L20

**Pull request merged**
