### PR TITLE
drop centos7, ubuntu1804, debian10

### PR DESCRIPTION
**Pull request by will-moore**
just testing...

### CODE REVIEW

**Comment by will-moore** [comment]
Build fails on `+ sudo pip install -r requirements.txt`
The only dependency there is `ome-ansible-molecule`,
which looks like it's only job is to install dependencies:
https://github.com/ome/ome-ansible-molecule/blob/master/setup.py has:
```
    install_requires=[
        'ansible==2.10.7',
        'docker-compose==1.26.2',
        'molecule==2.22',
        'jmespath==0.10.0',
        'passlib==1.7.4; sys_platform=="darwin"',
        # https://github.com/ansible-community/ansible-lint/issues/1795
        "rich<11.0.0",
    ],
```

<details><summary>Error on install of anyconfig==0.9.7</summary>
```
...
Collecting anyconfig==0.9.7
  Downloading anyconfig-0.9.7.tar.gz (97 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 KB 38.3 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-7pgou9kt/anyconfig_9e4091e1b7074f93a8e16323b9ef6546/setup.py", line 12, in <module>
          from anyconfig.globals import PACKAGE, VERSION
        File "/tmp/pip-install-7pgou9kt/anyconfig_9e4091e1b7074f93a8e16323b9ef6546/anyconfig/__init__.py", line 20, in <module>
          from .api import (
        File "/tmp/pip-install-7pgou9kt/anyconfig_9e4091e1b7074f93a8e16323b9ef6546/anyconfig/api.py", line 77, in <module>
          import anyconfig.backends
        File "/tmp/pip-install-7pgou9kt/anyconfig_9e4091e1b7074f93a8e16323b9ef6546/anyconfig/backends.py", line 16, in <module>
          import anyconfig.ioinfo
        File "/tmp/pip-install-7pgou9kt/anyconfig_9e4091e1b7074f93a8e16323b9ef6546/anyconfig/ioinfo.py", line 16, in <module>
          import anyconfig.utils
        File "/tmp/pip-install-7pgou9kt/anyconfig_9e4091e1b7074f93a8e16323b9ef6546/anyconfig/utils.py", line 385, in <module>
          _LIST_LIKE_TYPES = (collections.Iterable, collections.Sequence)
      AttributeError: module 'collections' has no attribute 'Iterable'
      [end of output]
```
</details>

Current version is `anyconfig 0.13.0`

**Comment by jburel** [comment]
see https://github.com/ome/omeroweb-install/pull/86

**Comment by will-moore** [comment]
Ah - Thanks. Any reason not to merge that?

**Comment by will-moore** [comment]
@jburel I can't figure out what's supposed to be in `omeroweb-install-ubuntu2004-ice3.6` after running:

```
$ ansible-playbook ansible/omeroweb-install.yml -i ansible/hosts/ubuntu2004-ice3.6
$ ansible-playbook ansible/omeroweb-install-doc.yml -i ansible/hosts/ubuntu2004-ice3.6
```
Those only generate a dir at
```
ansible/ubuntu2004-ice3.6
```
and the docs at:
```
doc/omeroweb-install-ubuntu2004-ice3.6.rst
```

But then the next step `$ OS=ubuntu2004 ./test/docker-build.sh` fails because `omeroweb-install-ubuntu2004-ice3.6` isn't found.

The only places that I can find a path like that are in:
 - `docker-build.sh` (where it failed above) with `cp ... omeroweb-install-${OS}-ice${ICEVER}`
 - `test_ansible.sh` (which is used later in the workflow to test, in `script.sh`
 - `Dockerfile_ubuntu2004` has `RUN ... omeroweb-install-ubuntu2004-ice${ICEVER}`  which is where it fails if you comment-out the `cp` step in `docker-build.sh`.

So I can only find places that *consume* that directory and not the place where it's generated??

**Comment by will-moore** [comment]
Having missed the https://github.com/ome/omeroweb-install#testing-in-docker notes, trying them now...

```
$ OS=centos7 ICEVER=3.6 WEBPREFIX=/omero TRAVIS=False .travis/before_install.sh
+ '[' '!' -z False ']'
.travis/before_install.sh: line 12: TRAVIS_OS_NAME: unbound variable
```

Seems `TRAVIS=False` is considered truthy! Better to omit it...

```
$ OS=centos7 ICEVER=3.6 WEBPREFIX=/omero .travis/before_install.sh
...
PLAY RECAP ************************************************************************************************************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
```

```
$ OS=centos7 ICEVER=3.6 WEBPREFIX=/omero DOCKER=true TRAVIS_OS_NAME=linux .travis/install.sh
```
Failed as before with `/tmp/omeroweb-install-test/omeroweb-install-centos7-ice3.6: No such file or directory`

<details> <summary>Full output</summary>

```
+ [[ linux == \l\i\n\u\x ]]
+ true
+ echo 'Testing in Docker!'
Testing in Docker!
+ ./test/docker-build.sh
+ OS=centos7
+ ICEVER=3.6
+ WEBPORT=
+ WEBPREFIX=/omero
+ WEBSESSION=
+ WEBSERVER_CONF=
+ WEBSERVER_NAME=
+ PYTHONVER=
+ CACHE=--no-cache
++ dirname ./test/docker-build.sh
+ path=./test
+ rm -rf ./test/omeroweb-install-test.zip
+ mkdir ./test/omeroweb-install-test
+ cp -r ./test/../centos7-ice3.6 ./test/omeroweb-install-test
+ cd ./test
+ zip -r omeroweb-install-test.zip omeroweb-install-test
  adding: omeroweb-install-test/ (stored 0%)
  adding: omeroweb-install-test/centos7-ice3.6/ (stored 0%)
  adding: omeroweb-install-test/centos7-ice3.6/nginx.sh (deflated 46%)
  adding: omeroweb-install-test/centos7-ice3.6/install.sh (deflated 37%)
  adding: omeroweb-install-test/centos7-ice3.6/web_session_configure.sh (deflated 27%)
  adding: omeroweb-install-test/centos7-ice3.6/daemon.sh (deflated 49%)
  adding: omeroweb-install-test/centos7-ice3.6/virtualenv.sh (deflated 27%)
  adding: omeroweb-install-test/centos7-ice3.6/whitenoise_configuration.sh (deflated 29%)
  adding: omeroweb-install-test/centos7-ice3.6/deps.sh (deflated 39%)
  adding: omeroweb-install-test/centos7-ice3.6/create_user.sh (deflated 34%)
  adding: omeroweb-install-test/centos7-ice3.6/install_cors.sh (stored 0%)
  adding: omeroweb-install-test/centos7-ice3.6/selinux.sh (deflated 30%)
  adding: omeroweb-install-test/centos7-ice3.6/deps_web_session.sh (deflated 25%)
  adding: omeroweb-install-test/centos7-ice3.6/omeroweb_configure.sh (deflated 41%)
  adding: omeroweb-install-test/centos7-ice3.6/install_whitenoise.sh (stored 0%)
  adding: omeroweb-install-test/centos7-ice3.6/omero-web-systemd.service (deflated 45%)
  adding: omeroweb-install-test/centos7-ice3.6/cors_configuration.sh (deflated 49%)
  adding: omeroweb-install-test/centos7-ice3.6/deps_ice3.6.sh (deflated 19%)
  adding: omeroweb-install-test/centos7-ice3.6/install_web_session.sh (deflated 5%)
+ rm -rf ./test/omeroweb-install-test
+ IMAGE=omeroweb_install_test_centos7_ice3.6
+ echo 'Building image omeroweb_install_test_centos7_ice3.6'
Building image omeroweb_install_test_centos7_ice3.6
+ docker build -t omeroweb_install_test_centos7_ice3.6 --build-arg ICEVER=3.6 --build-arg WEBPORT= --build-arg WEBPREFIX=/omero --build-arg WEBSESSION= --build-arg WEBSERVER_CONF= --build-arg WEBSERVER_NAME= --build-arg PYTHONVER= --no-cache ./test -f ./test/Dockerfile_centos7
[+] Building 59.8s (11/11) FINISHED                                                                                                                                    
 => [internal] load build definition from Dockerfile_centos7                                                                                                      0.1s
 => => transferring dockerfile: 1.07kB                                                                                                                            0.0s
 => [internal] load .dockerignore                                                                                                                                 0.0s
 => => transferring context: 2B                                                                                                                                   0.0s
 => [internal] load metadata for docker.io/openmicroscopy/omero-ssh-c7:0.1.0                                                                                      1.9s
 => [1/7] FROM docker.io/openmicroscopy/omero-ssh-c7:0.1.0@sha256:5413186e4feeb35bde99cc0d204bc1b4f390a54b6d08ad65e8473430fe3c7360                               22.8s
 => => resolve docker.io/openmicroscopy/omero-ssh-c7:0.1.0@sha256:5413186e4feeb35bde99cc0d204bc1b4f390a54b6d08ad65e8473430fe3c7360                                0.0s
 => => sha256:2d694cf34fe857fc098ffd89bf34bc8b008d907671e56c839d576ca0fc11f35f 1.82kB / 1.82kB                                                                    0.0s
 => => sha256:eb8d20e06fb7f97454b93b1ad2266e69f78b9cb4552a99030c62a1534b9132a8 291B / 291B                                                                        0.0s
 => => sha256:5989106db7fbf3f693f916dcb13ee7a42b9a8f9a5d188e2168602766989b5f57 70.54MB / 70.54MB                                                                  0.0s
 => => sha256:ad0a17e6b65952d579bd433a00df996d5e51c40c6d85cf78d10122ca885ce494 7.24MB / 7.24MB                                                                    0.0s
 => => sha256:cfd24d124149fdaa72509c4aed572d262d96244c7ac38c233edbd041956575f0 465B / 465B                                                                        0.0s
 => => sha256:380ae8e3cf3844585b4209e04d8f9fe94a782e66b87de6a0cb0a0eceb787bac3 2.04kB / 2.04kB                                                                    0.0s
 => => extracting sha256:5989106db7fbf3f693f916dcb13ee7a42b9a8f9a5d188e2168602766989b5f57                                                                         2.2s
 => => extracting sha256:ad0a17e6b65952d579bd433a00df996d5e51c40c6d85cf78d10122ca885ce494                                                                         0.2s
 => => extracting sha256:cfd24d124149fdaa72509c4aed572d262d96244c7ac38c233edbd041956575f0                                                                         0.0s
 => => extracting sha256:380ae8e3cf3844585b4209e04d8f9fe94a782e66b87de6a0cb0a0eceb787bac3                                                                         0.0s
 => => extracting sha256:2d694cf34fe857fc098ffd89bf34bc8b008d907671e56c839d576ca0fc11f35f                                                                         0.0s
 => => extracting sha256:eb8d20e06fb7f97454b93b1ad2266e69f78b9cb4552a99030c62a1534b9132a8                                                                         0.0s
 => [internal] load build context                                                                                                                                 0.0s
 => => transferring context: 6.95kB                                                                                                                               0.0s
 => [2/7] RUN userdel -r omero &&  rm -f /etc/sudoers.d/omero &&  echo 'root:omero' | chpasswd                                                                    0.7s
 => [3/7] ADD ./omeroweb-install-test.zip /tmp                                                                                                                    0.1s
 => [4/7] RUN yum -y install initscripts unzip                                                                                                                   33.0s
 => [5/7] RUN unzip /tmp/omeroweb-install-test.zip -d /tmp                                                                                                        0.5s
 => [6/7] RUN echo 'export container=docker' > /etc/profile.d/docker.sh                                                                                           0.2s 
 => ERROR [7/7] RUN ICEVER=3.6     WEBPORT= WEBPREFIX=/omero WEBSESSION=     WEBSERVER_CONF= WEBSERVER_NAME=     /tmp/omeroweb-install-test/omeroweb-install-cen  0.2s 
------                                                                                                                                                                 
 > [7/7] RUN ICEVER=3.6     WEBPORT= WEBPREFIX=/omero WEBSESSION=     WEBSERVER_CONF= WEBSERVER_NAME=     /tmp/omeroweb-install-test/omeroweb-install-centos7-ice3.6:  
#11 0.189 /bin/sh: /tmp/omeroweb-install-test/omeroweb-install-centos7-ice3.6: No such file or directory                                                               
------
executor failed running [/bin/sh -c ICEVER=$ICEVER     WEBPORT=$WEBPORT WEBPREFIX=$WEBPREFIX WEBSESSION=$WEBSESSION     WEBSERVER_CONF=$WEBSERVER_CONF WEBSERVER_NAME=$WEBSERVER_NAME     /tmp/omeroweb-install-test/omeroweb-install-centos7-ice${ICEVER}]: exit code: 127
```
</details>

**Comment by jburel** [comment]
I have adjusted the name in the docker file. I was only fixing ubuntu20.04 since that was the one you were looking at previously

**Comment by will-moore** [comment]
Strangely, using the latest commit of this branch, the 2nd step now worked (even though I only added comments etc):

```
$ OS=centos7 ICEVER=3.6 WEBPREFIX=/omero .travis/before_install.sh
...

TASK [Generate /Users/wmoore/Desktop/OMEROWEB_INSTALL/omeroweb-install/omeroweb-install-centos7-ice3.6] **************************************************************************
ok: [localhost]
...

$ OS=centos7 ICEVER=3.6 WEBPREFIX=/omero DOCKER=true TRAVIS_OS_NAME=linux .travis/install.sh
...
+ cd ./test
+ zip -r omeroweb-install-test.zip omeroweb-install-test
  adding: omeroweb-install-test/ (stored 0%)
  adding: omeroweb-install-test/centos7-ice3.6/ (stored 0%)
  adding: omeroweb-install-test/centos7-ice3.6/nginx.sh (deflated 46%)
  adding: omeroweb-install-test/centos7-ice3.6/install.sh (deflated 37%)
  adding: omeroweb-install-test/centos7-ice3.6/web_session_configure.sh (deflated 27%)
  adding: omeroweb-install-test/centos7-ice3.6/daemon.sh (deflated 49%)
  adding: omeroweb-install-test/centos7-ice3.6/virtualenv.sh (deflated 27%)
  adding: omeroweb-install-test/centos7-ice3.6/whitenoise_configuration.sh (deflated 29%)
  adding: omeroweb-install-test/centos7-ice3.6/deps.sh (deflated 39%)
  adding: omeroweb-install-test/centos7-ice3.6/create_user.sh (deflated 34%)
  adding: omeroweb-install-test/centos7-ice3.6/install_cors.sh (stored 0%)
  adding: omeroweb-install-test/centos7-ice3.6/selinux.sh (deflated 30%)
  adding: omeroweb-install-test/centos7-ice3.6/deps_web_session.sh (deflated 25%)
  adding: omeroweb-install-test/centos7-ice3.6/omeroweb_configure.sh (deflated 41%)
  adding: omeroweb-install-test/centos7-ice3.6/install_whitenoise.sh (stored 0%)
  adding: omeroweb-install-test/centos7-ice3.6/omero-web-systemd.service (deflated 45%)
  adding: omeroweb-install-test/centos7-ice3.6/cors_configuration.sh (deflated 49%)
  adding: omeroweb-install-test/centos7-ice3.6/deps_ice3.6.sh (deflated 19%)
  adding: omeroweb-install-test/centos7-ice3.6/install_web_session.sh (deflated 5%)
  adding: omeroweb-install-test/omeroweb-install-centos7-ice3.6 (deflated 61%)
+ rm -rf ./test/omeroweb-install-test
...
 => => transferring context: 7.61kB                                                                                                                                          0.0s
 => [2/7] RUN userdel -r omero &&  rm -f /etc/sudoers.d/omero &&  echo 'root:omero' | chpasswd                                                                               0.4s
 => [3/7] ADD ./omeroweb-install-test.zip /tmp                                                                                                                               0.0s
 => [4/7] RUN yum -y install initscripts unzip                                                                                                                              62.5s
 => [5/7] RUN unzip /tmp/omeroweb-install-test.zip -d /tmp                                                                                                                   0.3s
 => [6/7] RUN echo 'export container=docker' > /etc/profile.d/docker.sh                                                                                                      0.2s 
 => [7/7] RUN ICEVER=3.6     WEBPORT= WEBPREFIX=/omero WEBSESSION=     WEBSERVER_CONF= WEBSERVER_NAME=     /tmp/omeroweb-install-test/omeroweb-install-centos7-ice3.6      340.0s 
 => exporting to image                                                                                                                                                       2.7s 
 => => exporting layers                                                                                                                                                      2.6s 
 => => writing image sha256:347143c6b190b7a7ef2f823652193f2419de8a71d17d865faf83f26cf9d885c8                                                                                 0.0s 
 => => naming to docker.io/library/omeroweb_install_test_centos7_ice3.6                                                                                                      0.0s 
```

Trying 3rd step:

```
$ OS=centos7 ICEVER=3.6 WEBPREFIX=/omero DOCKER=true TRAVIS_OS_NAME=linux .travis/script.sh
+ [[ linux == \l\i\n\u\x ]]
+ true
+ echo 'Testing in Docker'
Testing in Docker
+ ./test/test_services.sh
+ OS=centos7
+ WEBSESSION=
+ WEBPREFIX=/omero
+ WEBPORT=80
+ ICEVER=3.6
+ CNAME=omeroweb_install_test_centos7_ice3.6
+ [[ darwin == \d\a\r\w\i\n ]]
+ docker run -d --privileged -p 8888:80 --name omeroweb_install_test_centos7_ice3.6 omeroweb_install_test_centos7_ice3.6
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
9b694e98526f3638c1be78a88a7d450e4e01f3bd0191a779baae74aaae7e3f4f
+ sleep 5
+ docker inspect -f '{{.State.Running}}' omeroweb_install_test_centos7_ice3.6
true
+ docker logs omeroweb_install_test_centos7_ice3.6
+ [[ darwin == \d\a\r\w\i\n ]]
+ curl -f -I http://localhost:8888/omero/webclient/login/
curl: (52) Empty reply from server
```

Looks like this isn't going to work on Mac

**Comment by will-moore** [comment]
OK, so I'm done with "testing" - This PR could be merged if useful?

**Pull request merged**
