### PR TITLE
Django redis

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
upgrade redis and fix ansible paths

### CODE REVIEW

**Comment by jburel** [comment]
is this PR ready for review?

**Comment by aleksandra-tarkowska** [comment]
This is ready to merge

**Comment by jburel** [comment]
Did someone review it?

**Comment by aleksandra-tarkowska** [comment]
it was listed last month, I don't know

**Comment by jburel** [comment]
Merging the PR then I will apply changes introduced in https://github.com/ome/omeroweb-install/pull/8 on top

**Pull request merged**
