### PR TITLE
upgrade redis

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
upgrade redis and fix ansible paths

zlib is not needed, I forgot to install xcode locally

### CODE REVIEW

**Comment by aleksandra-tarkowska** [comment]
@rleigh-codelibre any issues with that patch?

**Comment by rleigh-codelibre** [comment]
@aleksandra-tarkowska Why does zlib need installing?  It's present on the base system as /usr/lib/libz* and /usr/include/zlib.h.

**Comment by aleksandra-tarkowska** [comment]
yeah, xcode clt missing

**Comment by rleigh-codelibre** [comment]
Looks fine.  There's a missing newline at the end of the file.

**Pull request closed without merging**
