### PR TITLE
Initd

### PR DESCRIPTION
**Pull request by jburel**
This PR fixes the file used to start omero-web for both ubuntu and debian

The changes are tested by travis in PR #26 (ubuntu and debian build)
https://trello.com/c/jYST0HL6/133-omeroweb-install-virtualenv-systemd-service-file-doesnt-work

### CODE REVIEW

**Comment by jburel** [comment]
Changes in this PR tested by https://github.com/ome/omeroweb-install/pull/26

**Comment by jburel** [comment]
@mtbc: https://github.com/ome/omeroweb-install/pull/28/commits/80effe1463918915a71a5b8c64bad29d5c5b85cf  replaces ``dash`` (default in the docker image) by ``bash`` so we can use directly ``source`` instead of ``.`` in debian9
What do you think of that approach?

**Comment by mtbc** [comment]
It had never occurred to me to try avoiding `.`. :smiley: I'm not sure I understand the problem - do we instead need a `chsh` to change a user's default shell to bash or something when they next log in? (If the issue is in the current session then I'd guess we can just exec bash.) I think what you're doing is probably okay and reasonable, actually, it's just not something I'd seen before, so no blockers from me.

**Comment by mtbc** [comment]
Actually, I bet you're just manually doing pretty much what `dpkg-reconfigure dash` does? If so, certainly fine.

**Comment by jburel** [comment]
The problem is that we cannot use ``source`` to activate the virtualenv
so if the ``.`` is more normal. I will roll back the commit creating the symlink and replace source by ``.``

**Comment by jburel** [comment]
Latest commit tested by https://travis-ci.org/ome/omeroweb-install/builds/271955189?utm_source=github_status&utm_medium=notification

**Comment by rleigh-codelibre** [comment]
`.` is the correct syntax to use for sourcing to work universally, so this is the correct change.  `source` has always been a non-standard bash-specific extension.

**Comment by jburel** [comment]
last commit tested using https://travis-ci.org/ome/omeroweb-install/builds/272016382?utm_source=github_status&utm_medium=notification

**Comment by jburel** [comment]
i will need to remove the usage of source in the doc PR to avoid any confusion i.e. https://github.com/ome/omeroweb-install/pull/22

**Comment by mtbc** [comment]
Regarding testing script extracts: Where our scripts start with `#!/bin/bash` or similar it *might* help us to detect bashisms if we were to start with `#!/bin/bash --posix` instead.

**Comment by jburel** [comment]
I think we can do that in a follow up PR.

**Comment by jburel** [comment]
Travis is green
Merging so I can get https://github.com/ome/omeroweb-install/pull/22 green

**Pull request merged**
