### PR TITLE
Include scheme in omero.web.cors_origin_whitelist

### PR DESCRIPTION
**Pull request by manics**
See
- https://forum.image.sc/t/cors-white-listing/29457/14
- https://github.com/adamchainz/django-cors-headers#cors_origin_whitelist

### CODE REVIEW

**Comment by joshmoore** [comment]
The change certainly matches the feedback from Damir as well as the documentation, so in that sense, I'd say let's get this in. (Doc release needed)

But is there any infrastructure for testing these settings, say via a deployment example?

**Comment by manics** [comment]
Nothing at the moment. It could be added to one of the examples.

**Comment by joshmoore** [comment]
Thoughts on driving the release and the test forward?

**Comment by manics** [comment]
I thought the doc release was still coupled to the OMERO.server release?

**Comment by joshmoore** [comment]
Not that I know of. Guess it would be important to know that no doc PRs have been merged that don't match 5.6.x.

**Comment by manics** [comment]
I mean't I thought we couldn't do a docs releases without also doing a server release, has it changed?

**Comment by joshmoore** [comment]
I'm under impression that you docs can be released without a server release.

**Pull request merged**
