### PR TITLE
Doc steps

### PR DESCRIPTION
**Pull request by jburel**
Add new sections and fix some contents

see https://trello.com/c/nwwvjS6G/18-bin-omero-web-start-in-web-install-docs

### CODE REVIEW

**Comment by jburel** [comment]
Doc PR opened https://github.com/openmicroscopy/ome-documentation/pull/1845 to ease review

**Comment by will-moore** [comment]
Built https://github.com/openmicroscopy/ome-documentation/pull/1845 locally and used [docker centos7] (http://will-moore.github.io/omero-install-testing-with-docker/) to walk through
sysadmins/unix/install-web/walkthrough/omeroweb-install-centos7-ice3.6.html ...

Everything seemed to work pretty well...
I didn't find this very helpful
```
# Test installation e.g. https://github.com/openmicroscopy/omero-web-docker/blob/master/test_getweb.sh
```
Is the user supposed to copy that file and run it? Would that even work?
In the end I simply did ```curl -sL localhost:4080``` and it looked like I got the login page so this seemed OK. Maybe just have users do ```curl -sL localhost:4080 | grep "OMERO.web - Login"``` instead of pointing at test_getweb.sh?

At this point I also tried connecting with my host browser, but got nothing and realised we've not started nginx yet. Maybe the nginx section should come first?

I'm not sure if "Standalone OMERO.web" is the right title for that section? We're on the standalone OMERO.web page already. In this section we're Running/Starting/Testing OMERO.web. Maybe if this section is called "Running OMERO.web" then the following section is "Automatically Run OMERO.web"

NB: probably unrelated, but I set the server_list to connect to eel but I seem to have a very flaky connection and keep getting logged out. Maybe docker wierdness?

**Comment by will-moore** [comment]
Great - worked just fine and docs read well etc.
Maybe "Automatically Running OMERO.web" is a better title than "Running Automatically OMERO.web"?
Good to merge.

**Comment by jburel** [comment]
Will swap the order

**Comment by jburel** [comment]
@will-moore done

**Comment by will-moore** [comment]
Great, thx. 👍

**Pull request merged**
