### PR TITLE
Ubuntu2004

### PR DESCRIPTION
**Pull request by jburel**
Add support for ubuntu 20.04

Check that travis is green

### CODE REVIEW

**Comment by manics** [comment]
Travis is passing.
How are you dealing with the IceSSL issue (`omero-certificates` vs setting `@SECLEVEL=0`)?

**Comment by jburel** [comment]
This is what I mentioned on the call yesterday, I did not use ``omero-certificates`` in the doc since it was not used in any of the guides. I was thinking to update the various guides and replace the patch 
```
omero config set omero.glacier2.IceSSL.Ciphers HIGH:ADH:@SECLEVEL=0
```
by the usage of ``omero-certificates``

**Comment by manics** [comment]
For a separate PR then.

**Comment by jburel** [comment]
Thanks @manics

**Pull request merged**
