### PR TITLE
Doc fix

### PR DESCRIPTION
**Pull request by jburel**
* Fix wording of section installing web requirements in virtual env
 * Give an example of webprefix, doc only

See  https://trello.com/c/iF5W5P64/95-2x-install-virtualenv-headings

cc @hflynn @kennethgillen 
When the page is generated, we will have

```
    OMERO_USER=omero
    WEBPORT=80
    WEBSERVER_NAME=localhost
    WEBPREFIX=/omero
```
and

```
Install in the virtualenv created previously (run as root)::
    
    /home/omero/omerowebvenv/bin/pip install --upgrade -r /home/omero/OMERO.py/share/web/requirements-py27.txt

```

### CODE REVIEW

**Comment by hflynn** [comment]
👍

**Comment by jburel** [comment]
I moved the value now it will show up
```
Configure OMERO.web and generate nginx template (run as omero)::
    
    source /home/omero/omerowebvenv/bin/activate
    # By default no value is set for WEBPREFIX but for example it can be set to /omero
    if [[ $WEBPREFIX = *[!\ ]* ]]; then
        /home/omero/OMERO.py/bin/omero config set omero.web.prefix "${WEBPREFIX}"
        /home/omero/OMERO.py/bin/omero config set omero.web.static_url "${WEBPREFIX}/static/"
    fi
```

**Comment by jburel** [comment]
Travis failure is not related to the changes. I have opened a PR to fix that.

**Comment by hflynn** [comment]
Looks good

**Comment by jburel** [comment]
Merging now that travis is green

**Pull request merged**
