### PR TITLE
Include PATH in omero-web-systemd.service

### PR DESCRIPTION
**Pull request by manics**
Closes https://github.com/ome/ome-documentation/issues/2098

### CODE REVIEW

**Comment by joshmoore** [comment]
It's a bit unfortunate that it's required (is that fixable?) but the change itself looks straight-forward enough. If there are no objections, happy to merge and then roll then into the next update (ASAP).

**Comment by manics** [comment]
https://github.com/ome/omero-py/blob/b4bee5327cb94de2c3115fa0396941ef00878d7e/src/omero/cli.py#L1411-L1418
Maybe it depends on what `sys.executable` is set to?

**Comment by manics** [comment]
Perhaps before we merge this we should double check the setup in case it's a problem with the user's environment.

**Comment by joshmoore** [comment]
General :+1:

**Pull request merged**
