### PR TITLE
ansible version bump

### PR DESCRIPTION
**Pull request by jburel**
Bump ansible version

cc @joshmoore 

Check that travis is green

### CODE REVIEW

**Comment by jburel** [comment]
as I feared, travis did not like ansible 2.3.1

**Comment by joshmoore** [comment]
What was the error?

**Comment by joshmoore** [comment]
Restarted just in case.

**Comment by jburel** [comment]
Problem is coming from the doc generation
i have turned it off for test
will see if we can make progress on the doc front

**Comment by jburel** [comment]
The solution I have working locally is:
installed jinja2 2.9.x, install 'jinja2<2.9', version 2.8.1 is then installed
everything can work with ansible 2.3.2

**Comment by joshmoore** [comment]
Do you have a reference for the underlying jinja problem? (i.e. when we can unpin)

**Comment by jburel** [comment]
https://github.com/ansible/ansible/issues/27494 since to indicate it will be fixed in the next release

Current release is 2.9.6 and it does not work so the workaround might be for a short time only

Ideally I would like to adjust the way the doc generation work if at all possible
I don't think I will have time for 5.4

**Comment by joshmoore** [comment]
Status is green and the changes look sensible. Happy for this to go in. @manics did comment (unrelatedly?) that it may no longer be necessary to install our own docker. Do you want to try without, or handle that in a follow-up?

**Comment by manics** [comment]
I don't know how easy it is to get `services: [docker]` working with `matrix: [os: ...]` so best to leave it for later invetigation.

**Comment by joshmoore** [comment]
Fair enough.

**Pull request merged**
